/*
Kanthor SDK API

SDK API

API version: 1.0
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApplicationListRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationListRes{}

// ApplicationListRes struct for ApplicationListRes
type ApplicationListRes struct {
	Count *int32 `json:"count,omitempty"`
	Data []Application `json:"data,omitempty"`
}

// NewApplicationListRes instantiates a new ApplicationListRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationListRes() *ApplicationListRes {
	this := ApplicationListRes{}
	return &this
}

// NewApplicationListResWithDefaults instantiates a new ApplicationListRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationListResWithDefaults() *ApplicationListRes {
	this := ApplicationListRes{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ApplicationListRes) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationListRes) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ApplicationListRes) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *ApplicationListRes) SetCount(v int32) {
	o.Count = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApplicationListRes) GetData() []Application {
	if o == nil || IsNil(o.Data) {
		var ret []Application
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationListRes) GetDataOk() ([]Application, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApplicationListRes) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Application and assigns it to the Data field.
func (o *ApplicationListRes) SetData(v []Application) {
	o.Data = v
}

func (o ApplicationListRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationListRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableApplicationListRes struct {
	value *ApplicationListRes
	isSet bool
}

func (v NullableApplicationListRes) Get() *ApplicationListRes {
	return v.value
}

func (v *NullableApplicationListRes) Set(val *ApplicationListRes) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationListRes) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationListRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationListRes(val *ApplicationListRes) *NullableApplicationListRes {
	return &NullableApplicationListRes{value: val, isSet: true}
}

func (v NullableApplicationListRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationListRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


