/*
Kanthor SDK API

SDK API

API version: 1.0
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MessageCreateReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageCreateReq{}

// MessageCreateReq struct for MessageCreateReq
type MessageCreateReq struct {
	AppId *string `json:"app_id,omitempty"`
	Body map[string]interface{} `json:"body,omitempty"`
	Headers *map[string]string `json:"headers,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewMessageCreateReq instantiates a new MessageCreateReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageCreateReq() *MessageCreateReq {
	this := MessageCreateReq{}
	return &this
}

// NewMessageCreateReqWithDefaults instantiates a new MessageCreateReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageCreateReqWithDefaults() *MessageCreateReq {
	this := MessageCreateReq{}
	return &this
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *MessageCreateReq) GetAppId() string {
	if o == nil || IsNil(o.AppId) {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageCreateReq) GetAppIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *MessageCreateReq) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *MessageCreateReq) SetAppId(v string) {
	o.AppId = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *MessageCreateReq) GetBody() map[string]interface{} {
	if o == nil || IsNil(o.Body) {
		var ret map[string]interface{}
		return ret
	}
	return o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageCreateReq) GetBodyOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Body) {
		return map[string]interface{}{}, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *MessageCreateReq) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given map[string]interface{} and assigns it to the Body field.
func (o *MessageCreateReq) SetBody(v map[string]interface{}) {
	o.Body = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *MessageCreateReq) GetHeaders() map[string]string {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]string
		return ret
	}
	return *o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageCreateReq) GetHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *MessageCreateReq) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *MessageCreateReq) SetHeaders(v map[string]string) {
	o.Headers = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *MessageCreateReq) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageCreateReq) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *MessageCreateReq) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *MessageCreateReq) SetType(v string) {
	o.Type = &v
}

func (o MessageCreateReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageCreateReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppId) {
		toSerialize["app_id"] = o.AppId
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableMessageCreateReq struct {
	value *MessageCreateReq
	isSet bool
}

func (v NullableMessageCreateReq) Get() *MessageCreateReq {
	return v.value
}

func (v *NullableMessageCreateReq) Set(val *MessageCreateReq) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageCreateReq) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageCreateReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageCreateReq(val *MessageCreateReq) *NullableMessageCreateReq {
	return &NullableMessageCreateReq{value: val, isSet: true}
}

func (v NullableMessageCreateReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageCreateReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


