/*
Kanthor SDK API

SDK API

API version: 2022.1201.1701
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EndpointRuleCreateReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointRuleCreateReq{}

// EndpointRuleCreateReq struct for EndpointRuleCreateReq
type EndpointRuleCreateReq struct {
	ConditionExpression string `json:"condition_expression"`
	ConditionSource string `json:"condition_source"`
	EpId string `json:"ep_id"`
	Exclusionary bool `json:"exclusionary"`
	Name string `json:"name"`
	Priority int64 `json:"priority"`
}

type _EndpointRuleCreateReq EndpointRuleCreateReq

// NewEndpointRuleCreateReq instantiates a new EndpointRuleCreateReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointRuleCreateReq(conditionExpression string, conditionSource string, epId string, exclusionary bool, name string, priority int64) *EndpointRuleCreateReq {
	this := EndpointRuleCreateReq{}
	this.ConditionExpression = conditionExpression
	this.ConditionSource = conditionSource
	this.EpId = epId
	this.Exclusionary = exclusionary
	this.Name = name
	this.Priority = priority
	return &this
}

// NewEndpointRuleCreateReqWithDefaults instantiates a new EndpointRuleCreateReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointRuleCreateReqWithDefaults() *EndpointRuleCreateReq {
	this := EndpointRuleCreateReq{}
	return &this
}

// GetConditionExpression returns the ConditionExpression field value
func (o *EndpointRuleCreateReq) GetConditionExpression() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConditionExpression
}

// GetConditionExpressionOk returns a tuple with the ConditionExpression field value
// and a boolean to check if the value has been set.
func (o *EndpointRuleCreateReq) GetConditionExpressionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConditionExpression, true
}

// SetConditionExpression sets field value
func (o *EndpointRuleCreateReq) SetConditionExpression(v string) {
	o.ConditionExpression = v
}

// GetConditionSource returns the ConditionSource field value
func (o *EndpointRuleCreateReq) GetConditionSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConditionSource
}

// GetConditionSourceOk returns a tuple with the ConditionSource field value
// and a boolean to check if the value has been set.
func (o *EndpointRuleCreateReq) GetConditionSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConditionSource, true
}

// SetConditionSource sets field value
func (o *EndpointRuleCreateReq) SetConditionSource(v string) {
	o.ConditionSource = v
}

// GetEpId returns the EpId field value
func (o *EndpointRuleCreateReq) GetEpId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EpId
}

// GetEpIdOk returns a tuple with the EpId field value
// and a boolean to check if the value has been set.
func (o *EndpointRuleCreateReq) GetEpIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EpId, true
}

// SetEpId sets field value
func (o *EndpointRuleCreateReq) SetEpId(v string) {
	o.EpId = v
}

// GetExclusionary returns the Exclusionary field value
func (o *EndpointRuleCreateReq) GetExclusionary() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Exclusionary
}

// GetExclusionaryOk returns a tuple with the Exclusionary field value
// and a boolean to check if the value has been set.
func (o *EndpointRuleCreateReq) GetExclusionaryOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Exclusionary, true
}

// SetExclusionary sets field value
func (o *EndpointRuleCreateReq) SetExclusionary(v bool) {
	o.Exclusionary = v
}

// GetName returns the Name field value
func (o *EndpointRuleCreateReq) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EndpointRuleCreateReq) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EndpointRuleCreateReq) SetName(v string) {
	o.Name = v
}

// GetPriority returns the Priority field value
func (o *EndpointRuleCreateReq) GetPriority() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *EndpointRuleCreateReq) GetPriorityOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *EndpointRuleCreateReq) SetPriority(v int64) {
	o.Priority = v
}

func (o EndpointRuleCreateReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointRuleCreateReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["condition_expression"] = o.ConditionExpression
	toSerialize["condition_source"] = o.ConditionSource
	toSerialize["ep_id"] = o.EpId
	toSerialize["exclusionary"] = o.Exclusionary
	toSerialize["name"] = o.Name
	toSerialize["priority"] = o.Priority
	return toSerialize, nil
}

func (o *EndpointRuleCreateReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"condition_expression",
		"condition_source",
		"ep_id",
		"exclusionary",
		"name",
		"priority",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEndpointRuleCreateReq := _EndpointRuleCreateReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEndpointRuleCreateReq)

	if err != nil {
		return err
	}

	*o = EndpointRuleCreateReq(varEndpointRuleCreateReq)

	return err
}

type NullableEndpointRuleCreateReq struct {
	value *EndpointRuleCreateReq
	isSet bool
}

func (v NullableEndpointRuleCreateReq) Get() *EndpointRuleCreateReq {
	return v.value
}

func (v *NullableEndpointRuleCreateReq) Set(val *EndpointRuleCreateReq) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointRuleCreateReq) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointRuleCreateReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointRuleCreateReq(val *EndpointRuleCreateReq) *NullableEndpointRuleCreateReq {
	return &NullableEndpointRuleCreateReq{value: val, isSet: true}
}

func (v NullableEndpointRuleCreateReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointRuleCreateReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


