/*
Kanthor SDK API

SDK API

API version: 1.0
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EndpointCreateReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointCreateReq{}

// EndpointCreateReq struct for EndpointCreateReq
type EndpointCreateReq struct {
	AppId *string `json:"app_id,omitempty"`
	Method *string `json:"method,omitempty"`
	Name *string `json:"name,omitempty"`
	Uri *string `json:"uri,omitempty"`
}

// NewEndpointCreateReq instantiates a new EndpointCreateReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointCreateReq() *EndpointCreateReq {
	this := EndpointCreateReq{}
	return &this
}

// NewEndpointCreateReqWithDefaults instantiates a new EndpointCreateReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointCreateReqWithDefaults() *EndpointCreateReq {
	this := EndpointCreateReq{}
	return &this
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *EndpointCreateReq) GetAppId() string {
	if o == nil || IsNil(o.AppId) {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointCreateReq) GetAppIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *EndpointCreateReq) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *EndpointCreateReq) SetAppId(v string) {
	o.AppId = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *EndpointCreateReq) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointCreateReq) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *EndpointCreateReq) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *EndpointCreateReq) SetMethod(v string) {
	o.Method = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EndpointCreateReq) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointCreateReq) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EndpointCreateReq) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EndpointCreateReq) SetName(v string) {
	o.Name = &v
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *EndpointCreateReq) GetUri() string {
	if o == nil || IsNil(o.Uri) {
		var ret string
		return ret
	}
	return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointCreateReq) GetUriOk() (*string, bool) {
	if o == nil || IsNil(o.Uri) {
		return nil, false
	}
	return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *EndpointCreateReq) HasUri() bool {
	if o != nil && !IsNil(o.Uri) {
		return true
	}

	return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *EndpointCreateReq) SetUri(v string) {
	o.Uri = &v
}

func (o EndpointCreateReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointCreateReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppId) {
		toSerialize["app_id"] = o.AppId
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Uri) {
		toSerialize["uri"] = o.Uri
	}
	return toSerialize, nil
}

type NullableEndpointCreateReq struct {
	value *EndpointCreateReq
	isSet bool
}

func (v NullableEndpointCreateReq) Get() *EndpointCreateReq {
	return v.value
}

func (v *NullableEndpointCreateReq) Set(val *EndpointCreateReq) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointCreateReq) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointCreateReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointCreateReq(val *EndpointCreateReq) *NullableEndpointCreateReq {
	return &NullableEndpointCreateReq{value: val, isSet: true}
}

func (v NullableEndpointCreateReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointCreateReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


