/*
Kanthor SDK API

SDK API

API version: 1.0
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GatewayError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayError{}

// GatewayError struct for GatewayError
type GatewayError struct {
	Code *string `json:"code,omitempty"`
	Error *string `json:"error,omitempty"`
}

// NewGatewayError instantiates a new GatewayError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayError() *GatewayError {
	this := GatewayError{}
	return &this
}

// NewGatewayErrorWithDefaults instantiates a new GatewayError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayErrorWithDefaults() *GatewayError {
	this := GatewayError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GatewayError) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayError) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GatewayError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *GatewayError) SetCode(v string) {
	o.Code = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GatewayError) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayError) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GatewayError) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GatewayError) SetError(v string) {
	o.Error = &v
}

func (o GatewayError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableGatewayError struct {
	value *GatewayError
	isSet bool
}

func (v NullableGatewayError) Get() *GatewayError {
	return v.value
}

func (v *NullableGatewayError) Set(val *GatewayError) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayError) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayError(val *GatewayError) *NullableGatewayError {
	return &NullableGatewayError{value: val, isSet: true}
}

func (v NullableGatewayError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


