/*
Kanthor SDK API

SDK API

API version: 2022.1201.1701
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EndpointUpdateReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointUpdateReq{}

// EndpointUpdateReq struct for EndpointUpdateReq
type EndpointUpdateReq struct {
	Method string `json:"method"`
	Name string `json:"name"`
}

type _EndpointUpdateReq EndpointUpdateReq

// NewEndpointUpdateReq instantiates a new EndpointUpdateReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointUpdateReq(method string, name string) *EndpointUpdateReq {
	this := EndpointUpdateReq{}
	this.Method = method
	this.Name = name
	return &this
}

// NewEndpointUpdateReqWithDefaults instantiates a new EndpointUpdateReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointUpdateReqWithDefaults() *EndpointUpdateReq {
	this := EndpointUpdateReq{}
	return &this
}

// GetMethod returns the Method field value
func (o *EndpointUpdateReq) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *EndpointUpdateReq) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *EndpointUpdateReq) SetMethod(v string) {
	o.Method = v
}

// GetName returns the Name field value
func (o *EndpointUpdateReq) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EndpointUpdateReq) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EndpointUpdateReq) SetName(v string) {
	o.Name = v
}

func (o EndpointUpdateReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointUpdateReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["method"] = o.Method
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *EndpointUpdateReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"method",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEndpointUpdateReq := _EndpointUpdateReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEndpointUpdateReq)

	if err != nil {
		return err
	}

	*o = EndpointUpdateReq(varEndpointUpdateReq)

	return err
}

type NullableEndpointUpdateReq struct {
	value *EndpointUpdateReq
	isSet bool
}

func (v NullableEndpointUpdateReq) Get() *EndpointUpdateReq {
	return v.value
}

func (v *NullableEndpointUpdateReq) Set(val *EndpointUpdateReq) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointUpdateReq) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointUpdateReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointUpdateReq(val *EndpointUpdateReq) *NullableEndpointUpdateReq {
	return &NullableEndpointUpdateReq{value: val, isSet: true}
}

func (v NullableEndpointUpdateReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointUpdateReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


