/*
Kanthor SDK API

SDK API

API version: 1.0
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EndpointRuleListRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointRuleListRes{}

// EndpointRuleListRes struct for EndpointRuleListRes
type EndpointRuleListRes struct {
	Count int64 `json:"count"`
	Data []EndpointRule `json:"data"`
}

type _EndpointRuleListRes EndpointRuleListRes

// NewEndpointRuleListRes instantiates a new EndpointRuleListRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointRuleListRes(count int64, data []EndpointRule) *EndpointRuleListRes {
	this := EndpointRuleListRes{}
	this.Count = count
	this.Data = data
	return &this
}

// NewEndpointRuleListResWithDefaults instantiates a new EndpointRuleListRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointRuleListResWithDefaults() *EndpointRuleListRes {
	this := EndpointRuleListRes{}
	return &this
}

// GetCount returns the Count field value
func (o *EndpointRuleListRes) GetCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *EndpointRuleListRes) GetCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *EndpointRuleListRes) SetCount(v int64) {
	o.Count = v
}

// GetData returns the Data field value
func (o *EndpointRuleListRes) GetData() []EndpointRule {
	if o == nil {
		var ret []EndpointRule
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *EndpointRuleListRes) GetDataOk() ([]EndpointRule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *EndpointRuleListRes) SetData(v []EndpointRule) {
	o.Data = v
}

func (o EndpointRuleListRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointRuleListRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *EndpointRuleListRes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEndpointRuleListRes := _EndpointRuleListRes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEndpointRuleListRes)

	if err != nil {
		return err
	}

	*o = EndpointRuleListRes(varEndpointRuleListRes)

	return err
}

type NullableEndpointRuleListRes struct {
	value *EndpointRuleListRes
	isSet bool
}

func (v NullableEndpointRuleListRes) Get() *EndpointRuleListRes {
	return v.value
}

func (v *NullableEndpointRuleListRes) Set(val *EndpointRuleListRes) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointRuleListRes) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointRuleListRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointRuleListRes(val *EndpointRuleListRes) *NullableEndpointRuleListRes {
	return &NullableEndpointRuleListRes{value: val, isSet: true}
}

func (v NullableEndpointRuleListRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointRuleListRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


