/*
Kanthor SDK API

SDK API

API version: 1.0
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MessageCreateRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageCreateRes{}

// MessageCreateRes struct for MessageCreateRes
type MessageCreateRes struct {
	Id string `json:"id"`
}

type _MessageCreateRes MessageCreateRes

// NewMessageCreateRes instantiates a new MessageCreateRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageCreateRes(id string) *MessageCreateRes {
	this := MessageCreateRes{}
	this.Id = id
	return &this
}

// NewMessageCreateResWithDefaults instantiates a new MessageCreateRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageCreateResWithDefaults() *MessageCreateRes {
	this := MessageCreateRes{}
	return &this
}

// GetId returns the Id field value
func (o *MessageCreateRes) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MessageCreateRes) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MessageCreateRes) SetId(v string) {
	o.Id = v
}

func (o MessageCreateRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageCreateRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *MessageCreateRes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessageCreateRes := _MessageCreateRes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMessageCreateRes)

	if err != nil {
		return err
	}

	*o = MessageCreateRes(varMessageCreateRes)

	return err
}

type NullableMessageCreateRes struct {
	value *MessageCreateRes
	isSet bool
}

func (v NullableMessageCreateRes) Get() *MessageCreateRes {
	return v.value
}

func (v *NullableMessageCreateRes) Set(val *MessageCreateRes) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageCreateRes) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageCreateRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageCreateRes(val *MessageCreateRes) *NullableMessageCreateRes {
	return &NullableMessageCreateRes{value: val, isSet: true}
}

func (v NullableMessageCreateRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageCreateRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


