/*
Kanthor SDK API

SDK API

API version: 1.0
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MessageCreateRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageCreateRes{}

// MessageCreateRes struct for MessageCreateRes
type MessageCreateRes struct {
	Id *string `json:"id,omitempty"`
}

// NewMessageCreateRes instantiates a new MessageCreateRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageCreateRes() *MessageCreateRes {
	this := MessageCreateRes{}
	return &this
}

// NewMessageCreateResWithDefaults instantiates a new MessageCreateRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageCreateResWithDefaults() *MessageCreateRes {
	this := MessageCreateRes{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MessageCreateRes) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageCreateRes) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MessageCreateRes) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MessageCreateRes) SetId(v string) {
	o.Id = &v
}

func (o MessageCreateRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageCreateRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableMessageCreateRes struct {
	value *MessageCreateRes
	isSet bool
}

func (v NullableMessageCreateRes) Get() *MessageCreateRes {
	return v.value
}

func (v *NullableMessageCreateRes) Set(val *MessageCreateRes) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageCreateRes) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageCreateRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageCreateRes(val *MessageCreateRes) *NullableMessageCreateRes {
	return &NullableMessageCreateRes{value: val, isSet: true}
}

func (v NullableMessageCreateRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageCreateRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


