/*
Kanthor SDK API

SDK API

API version: 1.0
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EndpointCreateRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointCreateRes{}

// EndpointCreateRes struct for EndpointCreateRes
type EndpointCreateRes struct {
	AppId string `json:"app_id"`
	CreatedAt int64 `json:"created_at"`
	Id string `json:"id"`
	Method string `json:"method"`
	Name string `json:"name"`
	// To make the UI become friendly we will return the secret key after user create the new endpoint but we don't want to return that key everytime user request for the endpoint user must have specific permission to reveal the secret key of an endpoint
	SecretKey string `json:"secret_key"`
	UpdatedAt int64 `json:"updated_at"`
	Uri string `json:"uri"`
}

type _EndpointCreateRes EndpointCreateRes

// NewEndpointCreateRes instantiates a new EndpointCreateRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointCreateRes(appId string, createdAt int64, id string, method string, name string, secretKey string, updatedAt int64, uri string) *EndpointCreateRes {
	this := EndpointCreateRes{}
	this.AppId = appId
	this.CreatedAt = createdAt
	this.Id = id
	this.Method = method
	this.Name = name
	this.SecretKey = secretKey
	this.UpdatedAt = updatedAt
	this.Uri = uri
	return &this
}

// NewEndpointCreateResWithDefaults instantiates a new EndpointCreateRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointCreateResWithDefaults() *EndpointCreateRes {
	this := EndpointCreateRes{}
	return &this
}

// GetAppId returns the AppId field value
func (o *EndpointCreateRes) GetAppId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *EndpointCreateRes) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *EndpointCreateRes) SetAppId(v string) {
	o.AppId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *EndpointCreateRes) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EndpointCreateRes) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EndpointCreateRes) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *EndpointCreateRes) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EndpointCreateRes) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EndpointCreateRes) SetId(v string) {
	o.Id = v
}

// GetMethod returns the Method field value
func (o *EndpointCreateRes) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *EndpointCreateRes) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *EndpointCreateRes) SetMethod(v string) {
	o.Method = v
}

// GetName returns the Name field value
func (o *EndpointCreateRes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EndpointCreateRes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EndpointCreateRes) SetName(v string) {
	o.Name = v
}

// GetSecretKey returns the SecretKey field value
func (o *EndpointCreateRes) GetSecretKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretKey
}

// GetSecretKeyOk returns a tuple with the SecretKey field value
// and a boolean to check if the value has been set.
func (o *EndpointCreateRes) GetSecretKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretKey, true
}

// SetSecretKey sets field value
func (o *EndpointCreateRes) SetSecretKey(v string) {
	o.SecretKey = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *EndpointCreateRes) GetUpdatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *EndpointCreateRes) GetUpdatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *EndpointCreateRes) SetUpdatedAt(v int64) {
	o.UpdatedAt = v
}

// GetUri returns the Uri field value
func (o *EndpointCreateRes) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *EndpointCreateRes) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *EndpointCreateRes) SetUri(v string) {
	o.Uri = v
}

func (o EndpointCreateRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointCreateRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["app_id"] = o.AppId
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["id"] = o.Id
	toSerialize["method"] = o.Method
	toSerialize["name"] = o.Name
	toSerialize["secret_key"] = o.SecretKey
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["uri"] = o.Uri
	return toSerialize, nil
}

func (o *EndpointCreateRes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"app_id",
		"created_at",
		"id",
		"method",
		"name",
		"secret_key",
		"updated_at",
		"uri",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEndpointCreateRes := _EndpointCreateRes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEndpointCreateRes)

	if err != nil {
		return err
	}

	*o = EndpointCreateRes(varEndpointCreateRes)

	return err
}

type NullableEndpointCreateRes struct {
	value *EndpointCreateRes
	isSet bool
}

func (v NullableEndpointCreateRes) Get() *EndpointCreateRes {
	return v.value
}

func (v *NullableEndpointCreateRes) Set(val *EndpointCreateRes) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointCreateRes) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointCreateRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointCreateRes(val *EndpointCreateRes) *NullableEndpointCreateRes {
	return &NullableEndpointCreateRes{value: val, isSet: true}
}

func (v NullableEndpointCreateRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointCreateRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


