/*
Kanthor SDK API

SDK API

API version: 1.0
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EndpointListRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointListRes{}

// EndpointListRes struct for EndpointListRes
type EndpointListRes struct {
	Count *int32 `json:"count,omitempty"`
	Data []Endpoint `json:"data,omitempty"`
}

// NewEndpointListRes instantiates a new EndpointListRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointListRes() *EndpointListRes {
	this := EndpointListRes{}
	return &this
}

// NewEndpointListResWithDefaults instantiates a new EndpointListRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointListResWithDefaults() *EndpointListRes {
	this := EndpointListRes{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *EndpointListRes) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointListRes) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *EndpointListRes) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *EndpointListRes) SetCount(v int32) {
	o.Count = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EndpointListRes) GetData() []Endpoint {
	if o == nil || IsNil(o.Data) {
		var ret []Endpoint
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointListRes) GetDataOk() ([]Endpoint, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EndpointListRes) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Endpoint and assigns it to the Data field.
func (o *EndpointListRes) SetData(v []Endpoint) {
	o.Data = v
}

func (o EndpointListRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointListRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableEndpointListRes struct {
	value *EndpointListRes
	isSet bool
}

func (v NullableEndpointListRes) Get() *EndpointListRes {
	return v.value
}

func (v *NullableEndpointListRes) Set(val *EndpointListRes) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointListRes) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointListRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointListRes(val *EndpointListRes) *NullableEndpointListRes {
	return &NullableEndpointListRes{value: val, isSet: true}
}

func (v NullableEndpointListRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointListRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


