/*
Kanthor SDK API

SDK API

API version: 2022.1201.1701
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EndpointCreateReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointCreateReq{}

// EndpointCreateReq struct for EndpointCreateReq
type EndpointCreateReq struct {
	AppId string `json:"app_id"`
	Method string `json:"method"`
	Name string `json:"name"`
	Uri string `json:"uri"`
}

type _EndpointCreateReq EndpointCreateReq

// NewEndpointCreateReq instantiates a new EndpointCreateReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointCreateReq(appId string, method string, name string, uri string) *EndpointCreateReq {
	this := EndpointCreateReq{}
	this.AppId = appId
	this.Method = method
	this.Name = name
	this.Uri = uri
	return &this
}

// NewEndpointCreateReqWithDefaults instantiates a new EndpointCreateReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointCreateReqWithDefaults() *EndpointCreateReq {
	this := EndpointCreateReq{}
	return &this
}

// GetAppId returns the AppId field value
func (o *EndpointCreateReq) GetAppId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *EndpointCreateReq) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *EndpointCreateReq) SetAppId(v string) {
	o.AppId = v
}

// GetMethod returns the Method field value
func (o *EndpointCreateReq) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *EndpointCreateReq) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *EndpointCreateReq) SetMethod(v string) {
	o.Method = v
}

// GetName returns the Name field value
func (o *EndpointCreateReq) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EndpointCreateReq) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EndpointCreateReq) SetName(v string) {
	o.Name = v
}

// GetUri returns the Uri field value
func (o *EndpointCreateReq) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *EndpointCreateReq) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *EndpointCreateReq) SetUri(v string) {
	o.Uri = v
}

func (o EndpointCreateReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointCreateReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["app_id"] = o.AppId
	toSerialize["method"] = o.Method
	toSerialize["name"] = o.Name
	toSerialize["uri"] = o.Uri
	return toSerialize, nil
}

func (o *EndpointCreateReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"app_id",
		"method",
		"name",
		"uri",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEndpointCreateReq := _EndpointCreateReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEndpointCreateReq)

	if err != nil {
		return err
	}

	*o = EndpointCreateReq(varEndpointCreateReq)

	return err
}

type NullableEndpointCreateReq struct {
	value *EndpointCreateReq
	isSet bool
}

func (v NullableEndpointCreateReq) Get() *EndpointCreateReq {
	return v.value
}

func (v *NullableEndpointCreateReq) Set(val *EndpointCreateReq) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointCreateReq) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointCreateReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointCreateReq(val *EndpointCreateReq) *NullableEndpointCreateReq {
	return &NullableEndpointCreateReq{value: val, isSet: true}
}

func (v NullableEndpointCreateReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointCreateReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


