/*
Kanthor SDK API

SDK API

API version: 1.0
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EndpointUpdateRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointUpdateRes{}

// EndpointUpdateRes struct for EndpointUpdateRes
type EndpointUpdateRes struct {
	AppId string `json:"app_id"`
	CreatedAt int64 `json:"created_at"`
	Id string `json:"id"`
	Method string `json:"method"`
	Name string `json:"name"`
	UpdatedAt int64 `json:"updated_at"`
	Uri string `json:"uri"`
}

type _EndpointUpdateRes EndpointUpdateRes

// NewEndpointUpdateRes instantiates a new EndpointUpdateRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointUpdateRes(appId string, createdAt int64, id string, method string, name string, updatedAt int64, uri string) *EndpointUpdateRes {
	this := EndpointUpdateRes{}
	this.AppId = appId
	this.CreatedAt = createdAt
	this.Id = id
	this.Method = method
	this.Name = name
	this.UpdatedAt = updatedAt
	this.Uri = uri
	return &this
}

// NewEndpointUpdateResWithDefaults instantiates a new EndpointUpdateRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointUpdateResWithDefaults() *EndpointUpdateRes {
	this := EndpointUpdateRes{}
	return &this
}

// GetAppId returns the AppId field value
func (o *EndpointUpdateRes) GetAppId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *EndpointUpdateRes) GetAppIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *EndpointUpdateRes) SetAppId(v string) {
	o.AppId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *EndpointUpdateRes) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EndpointUpdateRes) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EndpointUpdateRes) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *EndpointUpdateRes) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EndpointUpdateRes) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EndpointUpdateRes) SetId(v string) {
	o.Id = v
}

// GetMethod returns the Method field value
func (o *EndpointUpdateRes) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *EndpointUpdateRes) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *EndpointUpdateRes) SetMethod(v string) {
	o.Method = v
}

// GetName returns the Name field value
func (o *EndpointUpdateRes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EndpointUpdateRes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EndpointUpdateRes) SetName(v string) {
	o.Name = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *EndpointUpdateRes) GetUpdatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *EndpointUpdateRes) GetUpdatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *EndpointUpdateRes) SetUpdatedAt(v int64) {
	o.UpdatedAt = v
}

// GetUri returns the Uri field value
func (o *EndpointUpdateRes) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *EndpointUpdateRes) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *EndpointUpdateRes) SetUri(v string) {
	o.Uri = v
}

func (o EndpointUpdateRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointUpdateRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["app_id"] = o.AppId
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["id"] = o.Id
	toSerialize["method"] = o.Method
	toSerialize["name"] = o.Name
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["uri"] = o.Uri
	return toSerialize, nil
}

func (o *EndpointUpdateRes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"app_id",
		"created_at",
		"id",
		"method",
		"name",
		"updated_at",
		"uri",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEndpointUpdateRes := _EndpointUpdateRes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEndpointUpdateRes)

	if err != nil {
		return err
	}

	*o = EndpointUpdateRes(varEndpointUpdateRes)

	return err
}

type NullableEndpointUpdateRes struct {
	value *EndpointUpdateRes
	isSet bool
}

func (v NullableEndpointUpdateRes) Get() *EndpointUpdateRes {
	return v.value
}

func (v *NullableEndpointUpdateRes) Set(val *EndpointUpdateRes) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointUpdateRes) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointUpdateRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointUpdateRes(val *EndpointUpdateRes) *NullableEndpointUpdateRes {
	return &NullableEndpointUpdateRes{value: val, isSet: true}
}

func (v NullableEndpointUpdateRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointUpdateRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


