/*
Kanthor SDK API

SDK API

API version: 1.0
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApplicationDeleteRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationDeleteRes{}

// ApplicationDeleteRes struct for ApplicationDeleteRes
type ApplicationDeleteRes struct {
	CreatedAt *int32 `json:"created_at,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	UpdatedAt *int32 `json:"updated_at,omitempty"`
	WsId *string `json:"ws_id,omitempty"`
}

// NewApplicationDeleteRes instantiates a new ApplicationDeleteRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationDeleteRes() *ApplicationDeleteRes {
	this := ApplicationDeleteRes{}
	return &this
}

// NewApplicationDeleteResWithDefaults instantiates a new ApplicationDeleteRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationDeleteResWithDefaults() *ApplicationDeleteRes {
	this := ApplicationDeleteRes{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ApplicationDeleteRes) GetCreatedAt() int32 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int32
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationDeleteRes) GetCreatedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ApplicationDeleteRes) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int32 and assigns it to the CreatedAt field.
func (o *ApplicationDeleteRes) SetCreatedAt(v int32) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApplicationDeleteRes) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationDeleteRes) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApplicationDeleteRes) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApplicationDeleteRes) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApplicationDeleteRes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationDeleteRes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApplicationDeleteRes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApplicationDeleteRes) SetName(v string) {
	o.Name = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ApplicationDeleteRes) GetUpdatedAt() int32 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int32
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationDeleteRes) GetUpdatedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ApplicationDeleteRes) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int32 and assigns it to the UpdatedAt field.
func (o *ApplicationDeleteRes) SetUpdatedAt(v int32) {
	o.UpdatedAt = &v
}

// GetWsId returns the WsId field value if set, zero value otherwise.
func (o *ApplicationDeleteRes) GetWsId() string {
	if o == nil || IsNil(o.WsId) {
		var ret string
		return ret
	}
	return *o.WsId
}

// GetWsIdOk returns a tuple with the WsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationDeleteRes) GetWsIdOk() (*string, bool) {
	if o == nil || IsNil(o.WsId) {
		return nil, false
	}
	return o.WsId, true
}

// HasWsId returns a boolean if a field has been set.
func (o *ApplicationDeleteRes) HasWsId() bool {
	if o != nil && !IsNil(o.WsId) {
		return true
	}

	return false
}

// SetWsId gets a reference to the given string and assigns it to the WsId field.
func (o *ApplicationDeleteRes) SetWsId(v string) {
	o.WsId = &v
}

func (o ApplicationDeleteRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationDeleteRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.WsId) {
		toSerialize["ws_id"] = o.WsId
	}
	return toSerialize, nil
}

type NullableApplicationDeleteRes struct {
	value *ApplicationDeleteRes
	isSet bool
}

func (v NullableApplicationDeleteRes) Get() *ApplicationDeleteRes {
	return v.value
}

func (v *NullableApplicationDeleteRes) Set(val *ApplicationDeleteRes) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationDeleteRes) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationDeleteRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationDeleteRes(val *ApplicationDeleteRes) *NullableApplicationDeleteRes {
	return &NullableApplicationDeleteRes{value: val, isSet: true}
}

func (v NullableApplicationDeleteRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationDeleteRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


