/*
Kanthor SDK API

SDK API

API version: 2022.1201.1701
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplicationUpdateReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationUpdateReq{}

// ApplicationUpdateReq struct for ApplicationUpdateReq
type ApplicationUpdateReq struct {
	Name string `json:"name"`
}

type _ApplicationUpdateReq ApplicationUpdateReq

// NewApplicationUpdateReq instantiates a new ApplicationUpdateReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationUpdateReq(name string) *ApplicationUpdateReq {
	this := ApplicationUpdateReq{}
	this.Name = name
	return &this
}

// NewApplicationUpdateReqWithDefaults instantiates a new ApplicationUpdateReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationUpdateReqWithDefaults() *ApplicationUpdateReq {
	this := ApplicationUpdateReq{}
	return &this
}

// GetName returns the Name field value
func (o *ApplicationUpdateReq) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApplicationUpdateReq) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApplicationUpdateReq) SetName(v string) {
	o.Name = v
}

func (o ApplicationUpdateReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationUpdateReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ApplicationUpdateReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationUpdateReq := _ApplicationUpdateReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationUpdateReq)

	if err != nil {
		return err
	}

	*o = ApplicationUpdateReq(varApplicationUpdateReq)

	return err
}

type NullableApplicationUpdateReq struct {
	value *ApplicationUpdateReq
	isSet bool
}

func (v NullableApplicationUpdateReq) Get() *ApplicationUpdateReq {
	return v.value
}

func (v *NullableApplicationUpdateReq) Set(val *ApplicationUpdateReq) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationUpdateReq) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationUpdateReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationUpdateReq(val *ApplicationUpdateReq) *NullableApplicationUpdateReq {
	return &NullableApplicationUpdateReq{value: val, isSet: true}
}

func (v NullableApplicationUpdateReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationUpdateReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


