/*
Kanthor SDK API

SDK API

API version: 1.0
Contact: support@kanthorlabs.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApplicationGetRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationGetRes{}

// ApplicationGetRes struct for ApplicationGetRes
type ApplicationGetRes struct {
	CreatedAt *int32 `json:"created_at,omitempty"`
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	UpdatedAt *int32 `json:"updated_at,omitempty"`
	WsId *string `json:"ws_id,omitempty"`
}

// NewApplicationGetRes instantiates a new ApplicationGetRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationGetRes() *ApplicationGetRes {
	this := ApplicationGetRes{}
	return &this
}

// NewApplicationGetResWithDefaults instantiates a new ApplicationGetRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationGetResWithDefaults() *ApplicationGetRes {
	this := ApplicationGetRes{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ApplicationGetRes) GetCreatedAt() int32 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int32
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationGetRes) GetCreatedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ApplicationGetRes) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int32 and assigns it to the CreatedAt field.
func (o *ApplicationGetRes) SetCreatedAt(v int32) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApplicationGetRes) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationGetRes) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApplicationGetRes) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApplicationGetRes) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApplicationGetRes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationGetRes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApplicationGetRes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApplicationGetRes) SetName(v string) {
	o.Name = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ApplicationGetRes) GetUpdatedAt() int32 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int32
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationGetRes) GetUpdatedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ApplicationGetRes) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int32 and assigns it to the UpdatedAt field.
func (o *ApplicationGetRes) SetUpdatedAt(v int32) {
	o.UpdatedAt = &v
}

// GetWsId returns the WsId field value if set, zero value otherwise.
func (o *ApplicationGetRes) GetWsId() string {
	if o == nil || IsNil(o.WsId) {
		var ret string
		return ret
	}
	return *o.WsId
}

// GetWsIdOk returns a tuple with the WsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationGetRes) GetWsIdOk() (*string, bool) {
	if o == nil || IsNil(o.WsId) {
		return nil, false
	}
	return o.WsId, true
}

// HasWsId returns a boolean if a field has been set.
func (o *ApplicationGetRes) HasWsId() bool {
	if o != nil && !IsNil(o.WsId) {
		return true
	}

	return false
}

// SetWsId gets a reference to the given string and assigns it to the WsId field.
func (o *ApplicationGetRes) SetWsId(v string) {
	o.WsId = &v
}

func (o ApplicationGetRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationGetRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.WsId) {
		toSerialize["ws_id"] = o.WsId
	}
	return toSerialize, nil
}

type NullableApplicationGetRes struct {
	value *ApplicationGetRes
	isSet bool
}

func (v NullableApplicationGetRes) Get() *ApplicationGetRes {
	return v.value
}

func (v *NullableApplicationGetRes) Set(val *ApplicationGetRes) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationGetRes) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationGetRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationGetRes(val *ApplicationGetRes) *NullableApplicationGetRes {
	return &NullableApplicationGetRes{value: val, isSet: true}
}

func (v NullableApplicationGetRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationGetRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


